local vars = require("hypr-vars")

require("hypr-debug").setup(vars)
require("hypr-env").setup(vars)
require("hypr-prefs").setup(vars)
require("hypr-render").setup(vars)
require("hypr-theme").setup(vars)
require("hypr-animations").setup(vars)
require("hypr-permissions").setup(vars)
require("hypr-input").setup(vars)
require("hypr-devices").setup(vars)
require("hypr-gestures").setup(vars)
require("hypr-layout").setup(vars)
require("hypr-monitors").setup(vars)
require("hypr-binds").setup(vars)
require("hypr-xwayland").setup(vars)
require("hypr-rules").setup(vars)
require("hypr-startup").setup(vars)
require("hypr-plugins").setup(vars)
