local vars = require("./vars.lua")

require("./debug.lua").setup(vars)
require("./env.lua").setup(vars)
require("./prefs.lua").setup(vars)
require("./render.lua").setup(vars)
require("./theme.lua").setup(vars)
require("./animations.lua").setup(vars)
require("./permissions.lua").setup(vars)
require("./input.lua").setup(vars)
require("./devices.lua").setup(vars)
require("./gestures.lua").setup(vars)
require("./layout.lua").setup(vars)
require("./monitors.lua").setup(vars)
require("./binds.lua").setup(vars)
require("./xwayland.lua").setup(vars)
require("./rules.lua").setup(vars)
require("./startup.lua").setup(vars)
require("./plugins.lua").setup(vars)
