$prevMod = SHIFT
$swapMod = CTRL

bind = $mainMod,                   tab, exec, $pypr layout_center prev
bind = $mainMod $prevMod,          tab, exec, $pypr layout_center next
bind = $mainMod $swapMod,          tab, swapnext,
bind = $mainMod $swapMod $prevMod, tab, swapnext, prev

