bind = $mainMod     , period, exec, $pypr toggle term
bind = $mainMod     , slash , exec, $pypr toggle file_manager
bind = $mainMod $meh, slash , exec, app2unit-term -- sudo $fileManager
bind = $mainMod     , M     , exec, $pypr toggle system_monitor
bind = $mainMod $meh, M     , exec, app2unit-term -- sudo $systemMonitor
bind = $mainMod     , U     , exec, $pypr toggle unit_monitor
bind = $mainMod     , E     , exec, $pypr toggle email
bind = $mainMod $meh, E     , exec, $pypr toggle calendar
bind = $mainMod     , S     , exec, $pypr toggle sms
bind = $mainMod     , V     , exec, app2unit-term -- $mediaplayer.local
bind = $mainMod $meh, V     , exec, app2unit-term -- $mediaplayer.remote
bind = $mainMod     , comma , exec, $pypr toggle browser

