bind = $mainMod $launcherMod, return, exec, rofi -show combi -modes combi -combi-modes "window,drun,run"
bind = $mainMod $launcherMod, A,      exec, rofi -show drun
bind = $mainMod $launcherMod, W,      exec, rofi -show window
bind = $mainMod $launcherMod, R,      exec, rofi -show run

